name: quick_log_money
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  bot_toast: ^4.1.3
  flutter:
    sdk: flutter
  hive: ^2.2.3
  json_annotation: ^4.9.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: Assets/Icon.png
  web:
    generate: true
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - Assets/Configs/
    - Assets/Icon.png
  fonts:
    - family: Ledger
      fonts:
        - asset: Assets/Ledger/Icon.ttf
